README.md

Updated date in README

---

.travis.yml

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/yaniswang/htmlhint/62)

chore(travis): use container-based infra and last stable node version

---

index.html
js/index.js

[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/yaniswang/htmlhint/61)

feat(site): add a download button to save configured htmlhintrc

---

bin/htmlhint

I add name of rule for output htmlhint

add name rule for cli

---

README.md

I fixed some of the headlines for easy reading.

Fixing typos in headlines

---

README.md
package.json
src/reporter.js

Some links have not been updated
I have not replaced links in files that are generated
- Replaced `https://github.com/yaniswang/HTMLHint` with `https://github.com/thedaviddias/HTMLHint`

replaced old links

---

bin/htmlhint

at least in Windows
Before and after screenshot:

Fixed search of the config file in parent directories

---

README.md

**Fixes**: #
Add discord badge
- Add discord badge

docs: add discord badge

---

README.md

**Fixes**: #
The README file was not updated for a long time. Need more rework but it's a first change.
- Add more divisions and text to enhance the quality of the README file.

docs: reorganise content inside README

---

src/core.js
src/htmlparser.js
src/rules/tag-pair.js

merge the master into development to keep the latest merge from the master in development
it was one commit behind

translated chinese comments (#261)

---

LICENSE.md

**Fixes**: #
-
-
-
👍 Thank you!

fix typo on Yanis name

---

.travis.yml
package.json

Add semantic release to automatically create a new tag, release when code is pushed on the master branch.
- Add semantic release package module
- Update travis to automatically deploy new version on NPM if master updated

refactor(htmlhint): add semantic release

---

index.html

**Fixes**: #
- Fixes htmlhint copyright year and URL
- remove unneeded type=javascript from scripts
- add canonical URL (good for SEO)
- update GitHub repo URLs
-
👍 Thank you!

update links and minor fixes

---

README.md

Just fixing a minor problem in the README.md file in which the internal link were broken (in the ToC).
:)

Fixing internal links in the ToC

---

package-lock.json
package.json

**Fixes**: #313 
The snyk package is now in devdependencies instead or dependencies

feat(htmlhint): move snyk from dependencies to devdep (#313)

---

.snyk
package-lock.json
package.json

feat(htmlhint): remove snyk

---

dist/htmlhint.js
src/rules/index.js
src/rules/tagname-specialchars.js
test/rules/tagname-specialchars.spec.js

**Fixes**: #
Added rule to check for special characters in tag name. See (#146)
-
👍 Thank you!

fix(htmlhint): added rule for special characters in tag name (#146)

---

bin/formatters/html.js
dist/htmlhint.js
src/rules/attr-value-single-quotes.js
src/rules/index.js
test/rules/attr-value-single-quotes.spec.js

**Fixes**: #154 
-
👍 Thank you!

Attr value single quotes

---

index.html

**Fixes**: #
Fix typo duplication should be duplicated
-
👍 Thank you!

Fix typo duplication should be duplicated

---

package.json

**Fixes**: #
updates URLs in repository and bugs in package.json

updates URLs in repository and bugs in package.json

---

package-lock.json
package.json

**Fixes**: #
Fix commitizen and semantic-release to automate the process of releases

chore: update commitizen and semantic release

---

README.md

update links back to htmlhint.com

update links back to htmlhint.com

---

.github/stale.yml

Avoid having old issues staying in the backlog without next action.
Add stale config

docs: add stale config

---

.github/workflows/ci.yml
.github/workflows/release.yml
package-lock.json
package.json

Moving away from Travis and using Github actions.
- Add ci action
- Add release action using Semantic Release

chores: add CI Github action

---

index.html

change canonical link to https://htmlhint.com

change canonical link to https://htmlhint.com

---

package.json

Mocha wasn't testing using all spec files.
Add the path to the test files in the test script

fix: mocha not testing all files

---

src/rules/spec-char-escape.js
test/rules/spec-char-escape.spec.js

PR #144 initially created by @rbanffy
Add tests for checking & and HTML entities

test: add tests for HTML entities

---

.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/semantic.yml

Non semantic release commits block PR
Add semantic release config file to always validate the PR title, and ignore the commits.

chore: add missing semantic yml

---

.eslintrc.js
src/core.js
src/htmlparser.js
src/reporter.js
src/rules/alt-require.js
src/rules/attr-lowercase.js
src/rules/attr-no-unnecessary-whitespace.js
src/rules/attr-unsafe-chars.js
src/rules/attr-value-double-quotes.js
src/rules/attr-value-not-empty.js
src/rules/attr-value-single-quotes.js
src/rules/attr-whitespace.js
src/rules/id-class-value.js
src/rules/id-unique.js
src/rules/input-requires-label.js
src/rules/spec-char-escape.js
src/rules/src-not-empty.js
src/rules/tag-pair.js
test/rules/attr-no-unnecessary-whitespace.js
test/rules/id-class-value.spec.js
test/rules/script-disabled.spec.js
test/rules/spec-char-escape.spec.js
test/rules/tags-check.spec.js

Set eslint rule `one-var` to `never`
https://eslint.org/docs/rules/one-var
- Set eslint rule `one-var` to `never`

chore: add lint rule one-var:never

---

website/docusaurus.config.js
website/package.json

Missing plugins for docusaurus
- Add Google Analytics plugin
- Add sitemap plugin

fix: add missing plugins for docusaurus

---

website/docusaurus.config.js

Google analytics code was dupplicated.
- Removing google analytics plugin call
- Add playground link to old web interface
- Uncomment Hotjar
Fix #406

fix: dupplicate ga

---

.github/workflows/ci.yml

Trigger CI also for new type of branches
Trigger CI also for `beta` and `chore/**`

chore: update ci workflow

---

.github/workflows/release.yml

Add missing branches to github action release

fix: add missing branches to action release

---

.github/workflows/ci.yml
codecov.yml
package-lock.json
package.json

Add Codecov support
Add codecov to Github actions

chore: add coverage codecov

---

package.json

Exclude ts files in coverage
Exclude ts files in coverage

chore: update nyc ts

---

test/cli/formatters/checkstyle.spec.js
test/cli/formatters/compact.spec.js
test/cli/formatters/html.spec.js
test/cli/formatters/json.spec.js
test/cli/formatters/unix.spec.js

Currently the complete files are checked.
This is really heavy to read in the diff if there is an error.
This changes to check line by line
- Check line by line
---
_This also resolves an issue on windows in json formatter test_ 😏

test: check line by line

---

src/cli/htmlhint.ts

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45192
Update to new 7.1.2 and use the return type

chore: update glob types

---

CHANGELOG.md

fix: beta fix

---

src/cli/htmlhint.ts

Simplify `sep` replace
Ref: https://github.com/htmlhint/HTMLHint/pull/443#issuecomment-650074634

refactor: use `path.sep` simplify #443

---

docs/user-guide/configuration.md

Added a bit more detail to the configuration page at https://htmlhint.com/docs/user-guide/configuration.

docs: Improve configuration documentation

---

docs/user-guide/integrations/task-runner.md

Add super-linter to task-runner docs
REF: https://github.com/github/super-linter/pull/373

docs: add super-linter to task-runner docs

---

.prettierignore

Update ignore rules for Prettier file

docs: Update ignore rules for Prettier file

---

docs/user-guide/list-rules.md

Fix a few broken links in the docs.

docs: Fix broken links in List of rules page

---

docs/user-guide/rules/attr-value-double-quotes.md

Correcting an example for a rule violation. The description contains two identical examples (double quotes).

fix: Update attr-value-double-quotes.md

---

docs/user-guide/list-rules.md

Added `head` tag into documentation of `list-rules`  rule `title-require`

docs: list-rules: title-require: add head tag

---

.github/labeler.yml
.github/labels.yml
.github/workflows/labeler.yml
.github/workflows/sync-labels.yml

Add automatic labels for PR and a sync label file

chore: add label sync and labeler

---

src/core/rules/tagname-specialchars.ts

Fixes: #701
Change description (I used one from the website)

fix: tagname-specialchars rule description

---

CHANGELOG.md

fix changelog duplication

---

.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/test-release.yml

Newer versions of setup-node now have built-in caching based off actions/cache

chore(build): use caching in setup-node

---

.github/dependabot.yml
.github/workflows/labeler.yml
.github/workflows/production.yml
.github/workflows/test-release.yml
package.json

Few build files had diffs running prettier, so added the calls to prettier as part of the existing lint/fix that get called by CI

style: run prettier during lint

---

.github/dependabot.yml

Causing the CI to fail now, so fixes the doublequoting

chore(dependabot): correct quoting for prettier

---

commitizen.config.js
package-lock.json
package.json
src/cli/htmlhint.ts
src/core/htmlparser.ts
src/core/rules/attr-unsafe-chars.ts
src/core/rules/inline-script-disabled.ts

Bump prettier to latest, and fix the formatting changes

style: apply latest Prettier formatting

---

package-lock.json
package.json

Don't believe the types need to be a production dependency

chore: push @types/node-fetch to devDeps

---

package-lock.json

Corrected the odd repository url and added cleanup from `npm audit fix`

build: correct resolve url and npm audit

---

.npmrc
package-lock.json
package.json

Bump semantic release packages

chore(deps-dev): bump semantic-release packages

---

package-lock.json
package.json

chore(deps-dev): bump commitlint

---

package-lock.json
package.json

Bumped the version, and simplified hooks to match recommended calls from docs

chore: update lint-staged to v12

---

package-lock.json
package.json

chore(deps-dev): bump rollup packages

---

website/package-lock.json
website/package.json

Upgraded lockfile and removed unused devDeps

chore: upgrade website lockfile to v2

---

SECURITY.md
package-lock.json

docs: create SECURITY.md

---

.github/workflows/development.yml
.github/workflows/production.yml
codecov.yml
package.json

Trying fixing Codecov no showing diff in PRs

ci: fix codecov pr diff

---

.gitignore

File is leftover running the tests. Alternately the test should be cleaning this up

chore: ignore HTML fomatter output

---

package-lock.json
package.json
src/cli/htmlhint.ts

Since the dependabot PR tests fail, trying to also change the import to match the recommended version from their README

chore(cli): upgrade commander to v8

---

.husky/prepare-commit-msg

Trying workaround from https://github.com/commitizen/cz-cli/issues/634#issuecomment-780227672 to address current semantic release issue

chore: update hook for CI compatibility

---

.github/workflows/website.yml
docs/toc.md
website/docusaurus.config.js
website/package-lock.json
website/package.json

Add basic CI for the website to make sure it builds
- remove duplicate call to google-analytics plugin included with them
- fix links in TOC

chore: setup CI for website

---

.gitattributes
.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/test-release.yml

Currently it uses the OS name as a label but everything runs on Ubuntu

ci: correct CI matrix to run on different OS

---

website/package-lock.json
website/package.json

These apparently need to bump together and dependabot submits them separately

chore: bump docusarus to 2.0.0-beta.13

---

README.md

Remove broken roadmap link from README.md

chore: remove broken roadmap link from README.md

---

website/playground/index.html

Points to the parked domain. Not sure if this will auto-deploy, but we'll see

chore: update remaining htmlhint.io refs

---

codecov.yml

ci: remove gcov CodeCov config

---

.github/workflows/development.yml
.github/workflows/production.yml
.github/workflows/test-release.yml

- CI is always true https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
- Husky 7 removed the install env variable https://typicode.github.io/husky/#/?id=breaking-changes

ci: cleanup environtment variable

---

docs/user-guide/list-rules.md
docs/user-guide/rules/html-lang-require.md

Add missing documentation page

docs(html-lang-require): add missing documentation

---

docs/user-guide/list-rules.md
docs/user-guide/rules/script-disabled.md

docs(script-disabled): add missing documentation

---

package-lock.json
package.json

Already reference the @commitlint/cli which this just wraps around

chore: remove commitlint direct devDep

---

website/package-lock.json
website/package.json

Update the docosaurs, svgr, and npm audit for the website

chore: update website deps

---

.github/workflows/development.yml
.github/workflows/production.yml
jest.config.js

ci: timeout and filter cleanup

---

website/docusaurus.config.js
website/package-lock.json
website/package.json

chore(website): Update to docusaurus 2.0.0-beta.15

---

docs/user-guide/list-rules.md

Put the good description of `attr-sorted`

docs(list-rules): Fix text description

---

.github/workflows/development.yml
.github/workflows/production.yml

Removes Node 12 from CI/CD
Fixes: #1115

Remove Node 12 from CI/CD

---

CHANGELOG.md

fix: fix typos in CHANGELOG

---

README.md
SECURITY.md

and fix org name on SECURITY.md

fix: Prettier formatting on README

---

docs/user-guide/integrations/task-runner.md

docs: update task runners pages

---

docs/user-guide/list-rules.md
docs/user-guide/rules/inline-script-disabled.md

Just a simple typo fix in the docs.

Fix typo in the docs

---

README.md
website/docusaurus.config.js

Remove Discord links

---

docs/user-guide/rules/doctype-html5.md

- Fixes title
- Example of a violation

Docs: Update doctype-html5 rule page

---

README.md

Adds programatic use of linter in JavaScript code.

Programatic use of linter - Update README.md

---

README.md

- Fixes Prettier build issue
- Adds syntax highlighting to codeblocks
- Fixes programmatically typo (was programatically)

Docs: Fix minor issues on README.md

---

package-lock.json
package.json

REF: https://docs.npmjs.com/cli/v11/configuring-npm/package-json#funding

chore: Add funding field to package.json

---

website/docusaurus.config.js
website/package-lock.json
website/package.json

Fixes: #1542
I also sorted the package.json

Docs: Remove Google Analytics (UA-)

---

.eslintignore
.gitignore
.vscode/extensions.json
.vscode/settings.json

Adds VS Code settings & recommended extensions for development to make contributing easier.

chore: Add VSCode Settings & Extensions for development

---

.cspell.json
website/docs/user-guide/integrations/task-runner.md

Add categories, update MegaLinter capitalization and URL

Docs: Update task-runners

---

website/docs/user-guide/rules/tag-self-close.md

Adds content for the `tag-self-close` rule page

docs: Update tag-self-close page

---

package-lock.json
package.json

These are all minor/patch updates. With this change all dependencies are up-to-date in that way (when running `npm outdated`)

Update Dev Dependencies

---

.github/codeql/codeql-config.yml
package-lock.json
package.json

REF:
https://github.com/isaacs/rimraf/blob/main/CHANGELOG.md

DevDep: Update Rimraf

---

.vscode/settings.json
test/rules/documentation.spec.js
website/.htmlhintrc

Fixes issue introduced when we changed the rules pages from .md to .mdx

Tests: Fix failing docs test

---

website/src/content/docs/configuration.md
website/src/content/docs/rules/head-script-disabled.mdx
website/src/content/docs/rules/inline-style-disabled.mdx
website/src/content/docs/rules/tag-pair.mdx
website/src/content/docs/rules/tagname-lowercase.mdx
website/src/content/docs/usage/cli.md

- CLI for checking version is -V - not -v
- Add trailing slash to URLs
- Fix grammatical issue
- Expand configuration docs to provide example config and VS Code JSON schema

Docs: Minor fixes

---

package-lock.json
package.json
website/src/content/docs/changelog.mdx
website/src/content/docs/rules/button-type-require.mdx
website/src/content/docs/rules/meta-description-require.mdx
website/src/content/docs/rules/meta-viewport-require.mdx

Release v1.4.0

---

.gemini/config.yaml
.gitignore
website/babel.config.js
website/src/content/docs/rules/inline-script-disabled.mdx
website/src/content/docs/vs-code-extension.mdx
website/src/custom.css

- Remove unneeded `babel.config.js` (was for Docusaurus)
- Nicer code block formatting for rules pages (valid and invalid)
- Minor config updates

Docs Updates

---

package-lock.json
package.json
website/src/content/docs/changelog.mdx
website/src/content/docs/rules/frame-title-require.mdx
website/src/content/docs/rules/meta-charset-require.mdx
website/src/content/docs/usage/cli.md

- Update package.json version
- Adds Changelog
- Unhide the two new rules

Release v1.5.0

---

website/src/content/docs/index.mdx
website/src/content/docs/rules/index.mdx

`frame-title-require` was missing. Thanks for spotting @Spixmaster !

Docs: Add missing rule from 'all rules' page

---

package-lock.json
package.json
src/cli/formatters/sarif.sarif
test/cli/formatters/sarif.sarif

RE: https://github.com/nvuillam/node-sarif-builder/releases

Update Node SARIF Builder

---

.github/workflows/website.yml
website/package.json

This adds HTMLHint SARIF Upload to Website GH Action

Docs: Add HTMLHint SARIF Upload to Website GH Action
