htmlhint/HTMLHint

LICENSE.md, README.md
#52 Removed your copyrights for year 2014. This means anyone can copy code from 2014 and claim it's his.
This PR fixes it. In future update 2014-X.
As explained in http://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated
=> Correct copyright support in LICENSE.md

src/rules/alt-require.js, src/rules/attr-lowercase.js, src/rules/attr-no-duplication.js, src/rules/attr-unsafe-chars.js, src/rules/attr-value-double-quotes.js, src/rules/attr-value-not-empty.js, src/rules/doctype-first.js, src/rules/doctype-html5.js, src/rules/head-script-disabled.js, src/rules/href-abs-or-rel.js, src/rules/id-class-ad-disabled.js, src/rules/id-class-value.js, src/rules/id-unique.js, src/rules/space-tab-mixed-disabled.js, src/rules/src-not-empty.js, src/rules/style-disabled.js, src/rules/tag-pair.js, src/rules/tag-self-close.js, src/rules/tagname-lowercase.js
Made the descriptions and error messages of rules more clear to people.
=> Rule copyediting

bin/htmlhint
White trying to integrate HTMLHint with SublimeLinter I found an issue with the executable for HTMLHint. As it stands HTMLHint will only process files with an .html extension (due to test on line 97 of current executable). To integrate with Sublime and allow the plugin to lint any file (e.g handlebars template etc.) I've made some changes to the executable so that if (and only if) you pass a file path via the command line it will process that file regardless of extension. If you pass nothing or a directory in it it will process files as before.
I've tried to implement the minimum to get this working, happy to discuss further, just let me know.
=> Make executable process file regardless of extension

bin/htmlhint
This commit adds a custom output format that defined in [GNU coding
standard][1] like this:
test.html:1.1: error: Doctype must be declared first.
test.html:5.35: error: Tag must be paired, missing: [ </p> ], start tag match failed [ <p> ] on line 5.
With this output format, text editors (such as Vim) can easily read
output from HTMLHint.
Sorry for lacking test case (I cannot find how to test bin options in this package).
[1]: https://www.gnu.org/prep/standards/standards.html#Errors
=> Add `gnu` custom output format

src/rules/attr-lowercase.js
When enabling the rule instead of using a boolean, use an array with the attributes (camelCased) that you want to ignore
```json
{
"attr-lowercase": ["viewBox"]
}
```
Fixes #28
=> Adding support for a white list of attributes that can be lower case.

package.json
Currently when installing HTMLHint, npm is warning about a deprecated version of minimatch.
This updates the jshint dependency which is the culprit of the warning.
=> Fix npm warning

LICENSE.md
You can list several copyrights in the license file in chronological order
Example: https://github.com/salsita/node-pg-migrate/blob/master/LICENSE
- added the old owner back to the license file
=> added the old owner back to the license file

src/core.js, src/htmlparser.js, src/rules/tag-pair.js
Most of the target group can speak English rather than Chinese
In addition, the code is also written in English
- changed chinese comments to english
=> translated chinese comments

bin/htmlhint
**Fixes**: #247 
The previous fix has broken the use of HTMLHint on Mac OSX.
- The duplication of path.resolve broked the correct path.
=> remove base resolve

bin/htmlhint
**Fixes**: #163 and #181
The fix was originally suggested by @phaux and make HTMLHint checking the root for the config file. 
- Change the tmpConfigFilve variable.
- Force the console to "break" if base is not found.
=> fix: update the check for root htmlhintrc

src/core.js
Fixes #345
HTMLhint does not work with nodejs v7, this fix resolves that.
Propose change is using Object.keys instead of Object.values, it is a very simple fix that will make HTMLhint usable by companies who are currently on nodejs v7 and 6.
=> Used Object.keys instead of Object.values

src/rules/attr-lowercase.js, test/rules/attr-lowercase.spec.js
**Fixes**: #228 #183  microsoft/vscode-htmlhint#34
```html
<p bind:tapTop="onTapTop" bind:moveBack="onBack"></p>
```
```json
{
"attr-lowercase" : ["/bind:.*/"]
}
```
will ignore all attributes  ` bind:*` now
The regex string configuration was referenced from stylelint.
=> feat(htmlhint): add RegExp and regex string

package.json
**Short description of what this resolves:**
Build script only generating minified version
Remove `--environment NODE_ENV:production` from `build:unmin` script
=> fix: dist generate htmlhint

src/rules/index.js, src/rules/tags-check.js, test/rules/tags-check.spec.js
Initial PR done by @SqrTT #184
**Short description of what this resolves:**
Add tags checking rule
=> feat: Add tags checking rule - allows specify rules for any tag and validate that

src/rules/attr-no-unnecessary-whitespace.js, src/rules/index.js, test/rules/attr-no-unnecessary-whitespace.js
Initial PR done by @jakewtaylor #220
Shows an error like:
`The attribute 'name' must not have spaces between the name and value.`
for code like:
```
type = "text"
type ="text"
type= "text"
```
This is valid:
```
type="text"
```
=> feat: added attr-no-unnecessary-whitespace rule

src/rules/index.js, src/rules/input-requires-label.js, test/rules/input-requires-label.spec.js
This is for accessibility. 
Some references:
- https://www.w3.org/WAI/tutorials/forms/instructions/
- http://webaim.org/techniques/forms/controls
=> feat: input-requires-label - All inputs require a label

docs/user-guide/list-rules.md
The title-require rule wasn't displaying as code (unlike the others)
=> docs: consistent formatting for rules

src/rules/attr-no-unnecessary-whitespace.js, test/rules/attr-no-unnecessary-whitespace.spec.js
The new "attr-no-unnecessary-whitespace" rule is not working correctly when there is equals symbol in the value, e.g.:
```html
<div title="a = a" />
```
Also the test file was wrongly named ".js" instead of ".spec.js".
Only the first "=" is checked and the test file is renamed correctly.
=> fix(attr-no-unnecessary-whitespace): fix when equals symbol in value

bin/htmlhint, test/executable.spec.js
The hint queue `drain`-function was incorrectly reassigned instead of being invoked.
- Invoke the `drain`-function correctly
=> fix: correctly call hint queue drain

package.json, website/docusaurus.config.js
Wrong URI for repo in package JSON
=> fix: fix url repo pkg

README.md
Replaces some dead links with regards to the wiki
Updated them with the closest match on htmlhint.com
=> docs: replaced wiki links with htmlhint.com links

README.md
Removes link to http://roadmap.htmlhint.io/  (no longer active)
=> docs: remove deadlink from README

package-lock.json, package.json
The `esm` dependency is no longer used anywhere
- Remove dependency `esm`
=> fix: remove unused dependency esm

package-lock.json, package.json, src/cli/formatter.ts, src/cli/formatters/compact.ts, src/cli/formatters/default.ts, src/cli/formatters/unix.ts, src/cli/htmlhint.ts
=> feat: use chalk instead of colors

src/cli/htmlhint.ts, test/cli/formatters/checkstyle.spec.js, test/cli/formatters/compact.spec.js, test/cli/formatters/html.spec.js, test/cli/formatters/unix.spec.js
In windows files are separated with `\` instead of `/`
This fix implemented a detection for windows and fix the unix style `/` for windows reports
Use `\` as file separator in windows
=> fix: windows path separator

docs/user-guide/getting-started.mdx
I noticed a small error in the getting started docs, where it shows how to run HTML Hint on all html files in the project, but the description said CSS files. 
Change CSS to HTML
=> docs: Change CSS to HTML in getting started example description 

docs/user-guide/list-rules.md, docs/user-guide/rules/input-requires-label.md
Hi :wave:!
According to the following rule ` input-requires-label` introduce in [`v0.13.0`](https://github.com/htmlhint/HTMLHint/blob/master/CHANGELOG.md#0130-2020-05-18), I'm submitting this Pull Request in order to update the documentation.
Added into the following section **Attributes** but please let me know if I have to move it into a different section. 
8023f29 - docs(user.guide): add input-requires-label
Rules has been introduce here: #159
Hope you'll find this useful.
Thank you :pray:!
=> docs(user.guide): add input-requires-label

docs/user-guide/getting-started.mdx, website/docusaurus.config.js
- Fixes example text to say `all the HTML files` instead of `all the CSS files`
- Fixes edit url to not go to a 404 page
P.S. if you don't mind, it would be greatly appreciated if you could also add the `hacktoberfest-accepted` label to this as I am participating in hacktoberfest. If not, I understand and it's no biggie
=> docs: Changes explanation text to match example

docs/user-guide/usage/options.md
Was looking at the docs on https://htmlhint.com/docs/user-guide/usage/options and found the the link was a 404
Found the right file in the repo https://github.com/htmlhint/HTMLHint/blob/master/docs/user-guide/configuration.md so adjusting the link target
=> fix: Link to configuration.md from options page

docs/user-guide/rules/attr-lowercase.md
The "violation" example was identical to the non-violation one.
Also adjusted wording and capitalization for clarity and correctness.
Fixes #531 (/cc @tag).
=> fix: improve documentation of attr-lowercase rule

docs/user-guide/list-rules.md
It resolver broken link in the documentation.
Link was fixed.
=> fix: broken link was fixed

website/sidebars.js
Very, very minor nit here, but the current rules [are not in alphabetical order in the menu on the left of the website](https://htmlhint.com/docs/user-guide/rules/alt-require).
Swap `attr-no-duplication` and `attr-lowercase` so they are in order
=> fix: Put rules in website menu in alphabetical order

docs/user-guide/integrations/task-runner.md
Add Mega-Linter in list of integrations
If you have a banner for HTMLHint, please notify me and I'll update [HTMLHint mega-linter page](https://nvuillam.github.io/mega-linter/descriptors/html_htmlhint/) :)
=> docs: Add Mega-Linter in list of integrations

docs/user-guide/rules/alt-require.md, docs/user-guide/rules/attr-lowercase.md, docs/user-guide/rules/space-tab-mixed-disabled.md
Updates a few docs with readability and examples
Markdown modifications to 'rules' docs
=> docs: user-guide rules updates

src/core/rules/html-lang-require.ts, test/rules/html-lang-require.spec.js
This PR made to resolve the next two issues:
1) html-lang-require rule show false result in valid cases (#653)
reason: because of reusing of the RegExp object which keeps the state after previous check
2) html-lang-require rule should not be applied to non HTML tag (#652)
=> fix: Unexpected behavior of the html lang require rule

docs/user-guide/integrations/editor.md
Remove Brackets HTMLHint (IDE deprecated)
=> docs: remove Brackets mention (deprecated)

README.md
Fix the broken `How To Use` link on the Readme.
=> fix: `How To Use` link.

.github/workflows/development.yml, .github/workflows/production.yml
Node 12, 14, 16, and 17 are the current supported NodeJS versions, so the matrix will excercise them all for regressions
=> chore(build): Run matrix on current node releases

.github/workflows/test-release.yml
The matrix values weren't being used by the tasks, so it's falling back to the default runner value
=> chore(build): remove redundant matrix

.github/dependabot.yml
Dependabot currently only runs on the root package.json and not any of the child package.json files. This adds the checks for the website subfolders
=> chore(build): add Dependabot for website packages

.github/workflows/development.yml, .github/workflows/production.yml
The linting shouldn't matter accross OS versions so pull it up to run once before all the matrix builds are triggered to fail fast
=> chore: run lint once for CI

package-lock.json
Now that Node 16 is the LTS release, it ships with NPM 8, which will now try to upgrade the lockfile when touched. This should be backward compatible with NPM clients on older Node versions
=> chore(build): upgrade package-lock version for latest NPM

.releaserc.json, package.json
The release was missing the release github plugin.
Moved configuration to a separated file.
=> chore(release): fix release github

package-lock.json, package.json
It seems like this is one of the recommended lint-staged/husky companion tools, but isn't currenly hooked in
=> chore: remove unused devDep pretty-quick

.github/dependabot.yml
Default limit is 5, so this will allow more PRs to be open at once. I think there may be less than 5 remaining, but in the future this will allow them to be opened, even if some others get stalled
=> chore: increase Dependabot PR limit

package-lock.json, package.json
Does move Typescript to the latest in the 3 branch, but mostly just moves the devDeps to carret ranges
=> chore: unpin remaining devDeps

.eslintrc.js, src/cli/formatter.ts
No funtional change to compiled code, except for sourceMap line
=> refactor(formatter): update order for @typescript-eslint/adjacent-overload-signatures

.eslintrc.js, src/core/htmlparser.ts
Looking at the compiled code, this doesn't change the output, since it trimmed it off anyway during compile
=> refactor(htmlparser): remove unused variable for @typescript-eslint/no-unused-vars

.github/workflows/development.yml, .github/workflows/production.yml
I expect this to fail currently, but the idea is to ensure the built files are included by PRs to show any changes to the output.
Maybe this isn't desired as the churn it might cause on those files
=> ci: ensure files are built

.github/workflows/production.yml, .github/workflows/test-release.yml
Pulling this from the other PR as it's unrelated. This started to have an issue as described over https://github.com/cycjimmy/semantic-release-action/issues/79#issuecomment-924607478
=> ci: sync semantic-release plugin versions

.github/workflows/development.yml, .github/workflows/production.yml, .github/workflows/test-release.yml
Noticed that the Dependabot PRs were triggering the main CI flow for website updates. There are some random failutes for that right now, but this will skip running on those content changes and just run the `website.yml` flow only
=> ci: don't trigger for website content

.github/workflows/production.yml, .github/workflows/test-release.yml, package-lock.json, package.json
They are installed by the GitHub Action to do the release each time
=> chore: remove direct semantic-release devDeps

src/core/rules/attr-whitespace.ts
Right now the following html ends with the message: "The attributes of [ id ] must not have trailing whitespace."
```html
<a id=" test"></a>
```
It doesn't really make sense since the whitespace is at the start.
This PR adds the "leading whitespace" possibility to the message.
=> fix: fix the message for `attr-whitespace`

.github/workflows/development.yml, .github/workflows/production.yml
Since the CLI tests on macOS seem to randomly fail waiting for the rest of stdin, retry 3 times instead of manually restarting the job
=> ci: retry coverage builds for flakey macOS runs

README.md
- Correct npm capitalization (should always be lowercase)
- Remove outdated node version requirements
- Use US English [spelling of Analyze](https://prowritingaid.com/analyse-or-analyze)
- html syntax highlighting in markdown example
=> fix: README tweaks

docs/user-guide/integrations/editor.md
Add link to the new VS Code extension:
https://marketplace.visualstudio.com/items?itemName=HTMLHint.vscode-htmlhint
=> fix: update Editor Extensions page on site

docs/user-guide/integrations/editor.md
typo on VS Code extension name.
https://marketplace.visualstudio.com/items?itemName=HTMLHint.vscode-htmlhintt
should be:
https://marketplace.visualstudio.com/items?itemName=HTMLHint.vscode-htmlhint
=> fix: typo on VS Code extension name

docs/user-guide/integrations/editor.md
The Atom HTMLHint plugin is archived, and the Atom editor is end-of-life and will be archived in December 2022 so may as well remove the link.
=> Docs: Remove Atom extension

docs/user-guide/rules/attr-whitespace.md
The rule is for whitespace inside an attribute, but the sample makes it look like it's also for surrounding whitespace
=> docs(attr-whitespace): remove example space

.github/dependabot.yml
Let's set it to run monthly or npm package checks instead of weekly to reduce the noise. We can remove the limit and default to default of 5... once a PR is merged it should auto-check again and open any new ones needed.
=> chore: change dependabot config

.github/workflows/development.yml, .github/workflows/production.yml, .github/workflows/test-release.yml, package-lock.json, package.json
Use v14, v16 and v18.
REF: https://github.com/nodejs/release#release-schedule
=> Update Node versions used on GitHub Actions

docs/user-guide/rules/tags-check.md
Closes #1211
Better describe `tags-check` rule, explaining what it does. This also explains all the customization options, and an example.
=> docs(tag-check): Add example and explain all options

.github/dependabot.yml
To reduce some of the Dependabot PRs, this will pull all minor/patch updates to single PRs, but leave majors on their own
=> chore: group Dependabot minor/patch updates

tsconfig.json
If you are working on a project where developers use different OSes (e.g.: Windows and Linux), enabling this property will prevent issues related to the file casing and how the files are referenced in the code.
REF: https://webhint.io/docs/user-guide/hints/hint-typescript-config/consistent-casing/
=> feat: tsconfig - forceConsistentCasingInFileNames

test/rules/documentation.spec.js
Add `website` to the path to fix the file not found error.
=> fix: documentation test

.github/workflows/codeql-analysis.yml, .github/workflows/development.yml, .github/workflows/production.yml, .github/workflows/spellcheck.yml, .github/workflows/super-linter.yml, .github/workflows/sync-labels.yml, .github/workflows/test-release.yml, .releaserc.json, README.md, website/docusaurus.config.js
`main` is the default branch name for GitHub and makes sense to use this.
Note: ignore failing test/linting because it's checking main but we haven't updated default branch in settings yet!
=> Change default branch from master to main

website/astro.config.mjs
The path for the site build has been updated to match what it was with Docusaurus to ensure it is published correctly.
=> Fix Site build path in astro.config.mjs

website/astro.config.mjs, website/src/content/docs/usage/cli.md, website/src/content/docs/usage/options.md
There was previously a Usage section on sidebar which somehow got missed when we migrated the site to Astro Starlight.
REF: https://web.archive.org/web/20250316190716/https://htmlhint.com/docs/user-guide/usage/cli
=> Docs: Add missing usage section from sidebar

.gemini/config.yaml, test/cli/formatters/compact.spec.js, test/cli/formatters/default.spec.js, test/cli/formatters/unix.spec.js
We added these console logs a few weeks ago to help debug when we had issues with tests completing, but all issues are resolved now so we can remove this to keep the CLI cleaner/faster.
Also added Gemini config to optimize the GitHub code reviews.
=> Tests: Remove console logs from tests

website/src/content/docs/rules/h1-require.mdx, website/src/custom.css
This rule hasn't been published to npmjs yet so let's hide it from sidebar. I added the New badge so when it is ready it'll show that badge. :-)
=> Docs: Hide h1 require rule

website/src/content/docs/changelog.mdx, website/src/content/docs/index.mdx
update changelog and homepage banner
=> docs update

.gitignore, package.json, src/cli/formatters/sarif.ts, test/cli/formatters/checkstyle.spec.js, test/cli/formatters/compact.spec.js, test/cli/formatters/default.spec.js, test/cli/formatters/html.spec.js, test/cli/formatters/json.spec.js, test/cli/formatters/junit.spec.js, test/cli/formatters/markdown.spec.js, test/cli/formatters/sarif.spec.js, test/cli/formatters/unix.spec.js
`htmlhint --report sarif` was outputting to the CLI but not creating a file, this PR fixes that.
The tests were failing so we fixed them.
=> fix: htmlhint sarif format now outputs a file

src/core/rules/attr-value-no-duplication.ts, test/rules/attr-value-no-duplication.spec.js, website/src/content/docs/index.mdx
Skip checking style tags, SVGs and media.
=> fix: Improved `attr-value-no-duplication` logic

package-lock.json, package.json, src/cli/formatters/sarif.ts, website/src/content/docs/changelog.mdx, website/src/content/docs/index.mdx
The SARIF formatter is now successfully including Markdown help content for the rules. 
The SARIF formatter wasn't properly outputting Markdown help for HTMLHint rules. The issues were:
- **Path Resolution Problem:** The code wasn't able to find the rule documentation MDX files because it was only looking in one specific location relative to the current working directory.
- **Error Handling:** The code silently failed when it couldn't find or process the documentation files, which made it difficult to debug.
- **Markdown Processing:** The code wasn't properly handling certain Markdown elements, particularly code blocks, which might have led to invalid output.
**Solutions Implemented:**
- **Multiple Path Resolution:** We now try multiple possible paths where the rule documentation might be …
=> fix: improve SARIF formatter (help text markdown)

examples/custom-rules/README.md, examples/custom-rules/example-rule.js, website/src/content/docs/usage/cli.md, website/src/content/docs/usage/custom-rules.mdx, website/src/content/docs/usage/options.md
This pull request introduces comprehensive support for custom HTMLHint rules, including examples, documentation, and CLI enhancements. The changes aim to make it easier for users to create, configure, and use custom rules to extend HTMLHint's functionality.
* [`examples/custom-rules/example-rule.js`](diffhunk://#diff-19a4e035810b6bbb5d756bb881e90e3c3acba4cf718d4026a337e74bfc7bd6b0R1-R47): Added an example custom rule that checks for accessibility attributes on images and validates class names against a configurable pattern. The rule demonstrates integration with the HTML parser and reporter.
* [`examples/custom-rules/README.md`](diffhunk://#diff-50b04ee56457a3468ffc679e011f57ebf1008ea2339fdb2246f85d13ca089bd8R1-R65): Documented the example custom rule, including its purpose, usage, …
=> docs: Add Custom Rules info

.cspell.json, website/astro.config.mjs, website/package-lock.json, website/package.json, website/src/custom.css
This pull request introduces a new plugin, `starlight-llms-txt`, to enhance functionality in the `website` project. It also includes updates to dependencies, configuration files, and styling to support the integration of the plugin and improve the user interface.
* **Added `starlight-llms-txt` plugin**: Updated `website/astro.config.mjs` to include the new plugin in the `plugins` array, enabling additional features for the project. (`[[1]](diffhunk://#diff-85cc15dfe103c8efb0d4d619255656cd2f2356feddf360e710ff326a71fdbcdeR4)`, `[[2]](diffhunk://#diff-85cc15dfe103c8efb0d4d619255656cd2f2356feddf360e710ff326a71fdbcdeR25)`)
* **Dependencies updated**: Added `starlight-llms-txt` to `website/package.json` and `website/package-lock.json` to manage the plugin's dependencies. …
=> docs: Add llms txt

.cspell.json, .github/workflows/codeql-analysis.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/publish.yml, .github/workflows/spellcheck.yml, .github/workflows/super-linter.yml, .github/workflows/sync-labels.yml, .github/workflows/test.yml, .github/workflows/website.yml
This pull request introduces a new GitHub Actions workflow for OSSF Scorecard supply-chain security analysis and updates all existing workflow dependencies to use specific commit SHAs for improved security and reproducibility. Additionally, it updates the spellchecker configuration to recognize "ossf" as a valid term.
**Security and CI improvements:**
* Added a new `.github/workflows/ossf-scorecard.yml` workflow to run OSSF Scorecard analysis on the repository, enhancing supply-chain security monitoring.
* Updated all GitHub Actions in workflow files (such as `actions/checkout`, `actions/setup-node`, `github/codeql-action`, and others) to use explicit commit SHAs instead of version tags, improving build reproducibility and mitigating the risk of compromised upstream actions. …
=> Update GitHub Actions
